# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Calculator2(object):
    def setupUi(self, Calculator2):
        Calculator2.setObjectName("Calculator2")
        Calculator2.resize(177, 197)
        Calculator2.setStyleSheet("background-color:Grey")
        self.centralwidget = QtWidgets.QWidget(Calculator2)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 10, 141, 141))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.num1 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.num1.setStyleSheet("background-color:white; placeholder:\"First number\";")
        self.num1.setObjectName("num1")
        self.verticalLayout.addWidget(self.num1)
        self.znak = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.znak.setStyleSheet("background-color:white")
        self.znak.setObjectName("znak")
        self.znak.addItem("")
        self.znak.addItem("")
        self.znak.addItem("")
        self.znak.addItem("")
        self.verticalLayout.addWidget(self.znak)
        self.num2 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.num2.setStyleSheet("background-color:white; placeholder:\"Second number\";")
        self.num2.setObjectName("num2")
        self.verticalLayout.addWidget(self.num2)
        self.btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn.setStyleSheet("background-color:white")
        self.btn.setObjectName("btn")
        self.verticalLayout.addWidget(self.btn)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setStyleSheet("color:white")
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        Calculator2.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Calculator2)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 177, 21))
        self.menubar.setObjectName("menubar")
        Calculator2.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Calculator2)
        self.statusbar.setObjectName("statusbar")
        Calculator2.setStatusBar(self.statusbar)

        self.retranslateUi(Calculator2)
        QtCore.QMetaObject.connectSlotsByName(Calculator2)

    def retranslateUi(self, Calculator2):
        _translate = QtCore.QCoreApplication.translate
        Calculator2.setWindowTitle(_translate("Calculator2", "MainWindow"))
        self.znak.setItemText(0, _translate("Calculator2", "+"))
        self.znak.setItemText(1, _translate("Calculator2", "-"))
        self.znak.setItemText(2, _translate("Calculator2", "*"))
        self.znak.setItemText(3, _translate("Calculator2", "/"))
        self.btn.setText(_translate("Calculator2", "Порахувати"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Calculator2 = QtWidgets.QMainWindow()
    ui = Ui_Calculator2()
    ui.setupUi(Calculator2)
    Calculator2.show()
    sys.exit(app.exec_())
